### ISSUE TITLE
go run wuyan.go admin route执行报错

### ISSUE THREAD

**Issue by vanwhebin** [wuyan94zl/go-api#1]
![image](https://user-images.githubusercontent.com/8357785/104083154-4d83c800-5277-11eb-82f6-4cc3c05ec72c.png)

**Comment by wuyan94zl** [comment]
.env.example  改为 .env

**Comment by wuyan94zl** [comment]
看一下 go run wuyan.go admin route 后面有没有什么数据，这个是没有找到路由文件，或者试试 go run wuyan.go admin route api

**Comment by zhaoguangshuai** [comment]
你是使用的macos系统的电脑吗？需要更改一些目录格式，他现在这种格式只支持windows系统的。
![image](https://user-images.githubusercontent.com/39761773/108725978-e2116380-7561-11eb-86ac-817e6558d3f3.png)

**Comment by wuyan94zl** [comment]
代码生成器改版了，详见readme.md
