### ISSUE TITLE
这个项目是参考的learnku的那个教程吗

### ISSUE THREAD

**Issue by iszmxw** [wuyan94zl/go-api#2]
# 感觉像参考的这里，不知道是不是的，我也比较喜欢这种命名
【[最适合 Laravel 开发者学习的 Go 实战课程](https://learnku.com/go/t/51595)】[https://learnku.com/go/t/51595](https://learnku.com/go/t/51595)

【[G01 Go 实战：Web 入门](https://learnku.com/courses/go-basic/1.15)】[https://learnku.com/courses/go-basic/1.15](https://learnku.com/courses/go-basic/1.15)

> 目录接口命名和引用的包大致一样

**Comment by wuyan94zl** [comment]
嗯，文件目录和配置是参考的

**Comment by iszmxw** [comment]
> 嗯，文件目录和配置是参考的

可以的，我也准备参照写一个rbac
