### ISSUE TITLE
用命令生成curd控制器，和curd控制器路由的文件的路径格式现在只支持Windows，不兼容macos系统的电脑路径格式

### ISSUE THREAD

**Issue by zhaoguangshuai** [wuyan94zl/go-api#4]
![image](https://user-images.githubusercontent.com/39761773/108728115-3a496500-7564-11eb-8ec8-315e693812f3.png)
![image](https://user-images.githubusercontent.com/39761773/108728606-b80d7080-7564-11eb-9f22-3a429b5dea09.png)

**Comment by wuyan94zl** [comment]
代码生成器改版了，详见readme.md
